import React, { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Badge, Button, Card, EmptyState, ErrorBanner, FormField, LoadingBlock, ModalSheet, SectionHeader, ToggleRow } from '../../components/ui';
import { useLanguage } from '../../context/LanguageContext';
import { shortDateTime } from '../../lib/format';
import { supabase } from '../../lib/supabase';
import { colors, spacing } from '../../theme';
import type { HolzRoom, IcalFeed } from '../../types';

export function IntegrationsView() {
  const { language } = useLanguage(); const de = language === 'de';
  const [feeds,setFeeds]=useState<IcalFeed[]>([]); const [rooms,setRooms]=useState<HolzRoom[]>([]); const [selected,setSelected]=useState<IcalFeed|null>(null); const [createOpen,setCreateOpen]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const [roomId,setRoomId]=useState(''); const [provider,setProvider]=useState('airbnb'); const [url,setUrl]=useState(''); const [enabled,setEnabled]=useState(true);
  async function load(){const [f,r]=await Promise.all([supabase.from('frankiholz_ical_feeds').select('*, frankiholz_rooms(name)').order('created_at'),supabase.from('frankiholz_rooms').select('*').order('sort_order')]);if(f.error)setError(f.error.message);else setFeeds((f.data??[]) as IcalFeed[]);if(!r.error){const x=(r.data??[]) as HolzRoom[];setRooms(x);if(!roomId&&x[0])setRoomId(x[0].id);}setLoading(false);}
  useEffect(()=>{load();},[]);
  async function sync(id?:string){setBusy(true);setError(null);let body:any={}; if(id){const feed=feeds.find(x=>x.id===id);if(feed)body={room_id:feed.room_id};}const {data,error:e}=await supabase.functions.invoke('frankiholz-sync-airbnb',{body});setBusy(false);if(e||data?.error)setError(data?.error??e?.message??'Sync failed');else await load();}
  async function create(){if(!roomId||!url.trim())return setError(de?'Zimmer und iCal-URL sind erforderlich.':'Room and iCal URL are required.');setBusy(true);const {error}=await supabase.from('frankiholz_ical_feeds').insert({room_id:roomId,provider:provider.trim()||'airbnb',feed_url:url.trim(),enabled});setBusy(false);if(error)setError(error.message);else{setCreateOpen(false);setUrl('');setProvider('airbnb');await load();}}
  async function save(){if(!selected)return;setBusy(true);const {error}=await supabase.from('frankiholz_ical_feeds').update({provider:selected.provider,feed_url:selected.feed_url,enabled:selected.enabled}).eq('id',selected.id);setBusy(false);if(error)setError(error.message);else{setSelected(null);await load();}}
  async function remove(feed:IcalFeed){Alert.alert(de?'Feed löschen?':'Delete feed?',feed.frankiholz_rooms?.name??feed.provider,[{text:de?'Zurück':'Back',style:'cancel'},{text:de?'Löschen':'Delete',style:'destructive',onPress:async()=>{const {error}=await supabase.from('frankiholz_ical_feeds').delete().eq('id',feed.id);if(error)setError(error.message);else{setSelected(null);await load();}}}]);}
  if(loading)return <LoadingBlock/>;
  return <><SectionHeader title={de?'Kalender-Synchronisierung':'Calendar sync'} subtitle={de?'Airbnb oder andere iCal-Feeds importieren und synchronisieren.':'Import and sync Airbnb or other iCal feeds.'} right={<Button compact variant="holz" title="+" onPress={()=>setCreateOpen(true)}/>} /><ErrorBanner message={error}/>
    <Button variant="secondary" loading={busy} title={de?'Alle Feeds jetzt synchronisieren':'Sync all feeds now'} onPress={()=>sync()}/><View style={{height:12}}/>
    {feeds.length===0?<EmptyState title={de?'Noch keine iCal-Feeds':'No iCal feeds yet'} message={de?'Füge den Export-Link von Airbnb oder einem anderen Buchungskalender hinzu.':'Add the export link from Airbnb or another booking calendar.'}/>:feeds.map(f=><Pressable key={f.id} onPress={()=>{setSelected({...f});setError(null);}}><Card><View style={styles.row}><View style={{flex:1}}><Text style={styles.title}>{f.frankiholz_rooms?.name??'Room'} · {f.provider}</Text><Text numberOfLines={1} style={styles.url}>{f.feed_url}</Text><Text style={styles.meta}>{de?'Letzte Sync':'Last sync'}: {shortDateTime(f.last_synced_at)}</Text>{f.last_error?<Text numberOfLines={2} style={styles.err}>{f.last_error}</Text>:null}</View><Badge text={f.enabled?(f.last_status||'enabled'):(de?'aus':'off')} tone={!f.enabled?'neutral':f.last_status==='error'?'danger':'success'}/></View></Card></Pressable>)}
    <ModalSheet visible={createOpen} title={de?'iCal-Feed hinzufügen':'Add iCal feed'} onClose={()=>setCreateOpen(false)}><ErrorBanner message={error}/><Text style={styles.label}>{de?'Zimmer':'Room'}</Text><View style={styles.rooms}>{rooms.map(r=><Pressable key={r.id} onPress={()=>setRoomId(r.id)} style={[styles.chip,roomId===r.id&&styles.chipActive]}><Text style={[styles.chipText,roomId===r.id&&{color:colors.white}]}>{r.name}</Text></Pressable>)}</View><FormField label={de?'Anbieter':'Provider'} value={provider} onChangeText={setProvider} placeholder="airbnb" autoCapitalize="none"/><FormField label="iCal URL" value={url} onChangeText={setUrl} autoCapitalize="none" keyboardType="url"/><ToggleRow label={de?'Aktiv':'Enabled'} value={enabled} onValueChange={setEnabled}/><Button variant="holz" loading={busy} title={de?'Feed speichern':'Save feed'} onPress={create}/></ModalSheet>
    <ModalSheet visible={!!selected} title={selected?`${selected.frankiholz_rooms?.name??'Room'} · ${selected.provider}`:''} onClose={()=>setSelected(null)}>{selected?<><ErrorBanner message={error}/><FormField label={de?'Anbieter':'Provider'} value={selected.provider} onChangeText={v=>setSelected({...selected,provider:v})}/><FormField label="iCal URL" value={selected.feed_url} onChangeText={v=>setSelected({...selected,feed_url:v})} autoCapitalize="none"/><ToggleRow label={de?'Aktiv':'Enabled'} value={selected.enabled} onValueChange={v=>setSelected({...selected,enabled:v})}/><Button variant="holz" loading={busy} title={de?'Änderungen speichern':'Save changes'} onPress={save}/><View style={{height:10}}/><Button variant="secondary" loading={busy} title={de?'Jetzt synchronisieren':'Sync now'} onPress={()=>sync(selected.id)}/><View style={{height:10}}/><Button variant="danger" title={de?'Feed löschen':'Delete feed'} onPress={()=>remove(selected)}/></>:null}</ModalSheet>
  </>;
}
const styles=StyleSheet.create({row:{flexDirection:'row',gap:10},title:{color:colors.text,fontWeight:'900',fontSize:14},url:{color:colors.muted,fontSize:10,marginTop:4},meta:{color:colors.muted,fontSize:11,marginTop:8},err:{color:colors.danger,fontSize:11,marginTop:6},label:{color:colors.text,fontWeight:'800',fontSize:13,marginBottom:8},rooms:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:spacing.lg},chip:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:12,paddingVertical:8},chipActive:{backgroundColor:colors.holz,borderColor:colors.holz},chipText:{color:colors.text,fontWeight:'800',fontSize:12}});
