import React, { useEffect, useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Button, Card, EmptyState, ErrorBanner, FormField, LoadingBlock, ModalSheet, SectionHeader, ToggleRow } from '../../components/ui';
import { useLanguage } from '../../context/LanguageContext';
import { euro } from '../../lib/format';
import { supabase } from '../../lib/supabase';
import { colors, radius } from '../../theme';
import type { HolzRoom } from '../../types';

type RoomImage = { id:string; room_id:string; storage_path:string; caption:string; sort_order:number };

export function RoomsView() {
  const { language } = useLanguage(); const de = language === 'de';
  const [rooms,setRooms] = useState<HolzRoom[]>([]); const [images,setImages] = useState<RoomImage[]>([]); const [selected,setSelected] = useState<HolzRoom|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  async function load(){ const [r,i]=await Promise.all([supabase.from('frankiholz_rooms').select('*').order('sort_order'),supabase.from('frankiholz_room_images').select('*').order('sort_order')]); if(r.error)setError(r.error.message);else setRooms((r.data??[]) as HolzRoom[]); if(!i.error)setImages((i.data??[]) as RoomImage[]); setLoading(false); }
  useEffect(()=>{load();},[]);
  async function save(){ if(!selected)return; setBusy(true);setError(null); const {error}=await supabase.from('frankiholz_rooms').update({name:selected.name,description:selected.description,base_price:Number(selected.base_price),max_guests:Number(selected.max_guests),active:selected.active}).eq('id',selected.id); setBusy(false); if(error)setError(error.message);else{setSelected(null);await load();} }
  async function addImage(){ if(!selected)return; const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:'images',allowsEditing:true,quality:0.82}); if(result.canceled)return; const asset=result.assets?.[0]; if(!asset){setError(de?'Kein Bild ausgewählt.':'No image selected.');return;} setBusy(true);setError(null); try{const body=await (await fetch(asset.uri)).arrayBuffer(); const ext=(asset.mimeType?.split('/')[1]||'jpg').replace('jpeg','jpg'); const path=`rooms/${selected.id}/${Date.now()}.${ext}`; const up=await supabase.storage.from('frankiholz-media').upload(path,body,{contentType:asset.mimeType||'image/jpeg'}); if(up.error)throw up.error; const ins=await supabase.from('frankiholz_room_images').insert({room_id:selected.id,storage_path:path,caption:'',sort_order:images.filter(x=>x.room_id===selected.id).length}); if(ins.error){await supabase.storage.from('frankiholz-media').remove([path]);throw ins.error;} await load(); }catch(e:any){setError(e.message??String(e));}finally{setBusy(false);} }
  async function removeImage(img:RoomImage){Alert.alert(de?'Bild löschen?':'Delete image?',img.caption||img.storage_path,[{text:de?'Zurück':'Back',style:'cancel'},{text:de?'Löschen':'Delete',style:'destructive',onPress:async()=>{setBusy(true);await supabase.storage.from('frankiholz-media').remove([img.storage_path]);const {error}=await supabase.from('frankiholz_room_images').delete().eq('id',img.id);setBusy(false);if(error)setError(error.message);else await load();}}]);}
  const publicUrl=(path:string)=>supabase.storage.from('frankiholz-media').getPublicUrl(path).data.publicUrl;
  if(loading)return <LoadingBlock/>;
  return <><SectionHeader title={de?'Zimmer':'Rooms'} subtitle={de?'Zimmerdaten, Grundpreise, Kapazität und Bilder pflegen.':'Manage room details, base prices, capacity and photos.'}/><ErrorBanner message={error}/>
    {rooms.length===0?<EmptyState title={de?'Keine Zimmer vorhanden':'No rooms found'}/>:rooms.map(r=><Pressable key={r.id} onPress={()=>{setSelected({...r});setError(null);}}><Card><View style={styles.row}><View style={{flex:1}}><Text style={styles.title}>{r.name}</Text><Text style={styles.sub}>{euro(r.base_price)} / {de?'Nacht':'night'} · {r.max_guests} {de?'Gäste':'guests'}</Text><Text numberOfLines={2} style={styles.desc}>{r.description||'—'}</Text></View><View style={[styles.status,r.active?styles.active:styles.inactive]}><Text style={[styles.statusText,{color:r.active?colors.success:colors.muted}]}>{r.active?(de?'AKTIV':'ACTIVE'):(de?'AUS':'OFF')}</Text></View></View></Card></Pressable>)}
    <ModalSheet visible={!!selected} title={selected?.name??''} onClose={()=>setSelected(null)}>{selected?<><ErrorBanner message={error}/><FormField label={de?'Zimmername':'Room name'} value={selected.name} onChangeText={v=>setSelected({...selected,name:v})}/><FormField label={de?'Beschreibung':'Description'} value={selected.description} onChangeText={v=>setSelected({...selected,description:v})} multiline/><FormField label={de?'Grundpreis pro Nacht (€)':'Base price per night (€)'} keyboardType="decimal-pad" value={String(selected.base_price)} onChangeText={v=>setSelected({...selected,base_price:Number(v.replace(',','.'))||0})}/><FormField label={de?'Max. Gäste':'Max guests'} keyboardType="number-pad" value={String(selected.max_guests)} onChangeText={v=>setSelected({...selected,max_guests:Number(v)||1})}/><ToggleRow label={de?'Online buchbar':'Bookable online'} value={selected.active} onValueChange={v=>setSelected({...selected,active:v})}/><Button variant="holz" loading={busy} title={de?'Zimmer speichern':'Save room'} onPress={save}/>
      <View style={styles.imageHeader}><Text style={styles.imageTitle}>{de?'Zimmerbilder':'Room photos'}</Text><Button compact variant="secondary" loading={busy} title={de?'+ Bild':'+ Photo'} onPress={addImage}/></View>
      <View style={styles.imageGrid}>{images.filter(x=>x.room_id===selected.id).map(img=><Pressable key={img.id} onLongPress={()=>removeImage(img)} style={styles.imageWrap}><Image source={{uri:publicUrl(img.storage_path)}} style={styles.image}/><Text style={styles.deleteHint}>{de?'Lange drücken zum Löschen':'Hold to delete'}</Text></Pressable>)}</View>
    </>:null}</ModalSheet>
  </>;
}
const styles=StyleSheet.create({row:{flexDirection:'row',gap:12},title:{fontSize:17,fontWeight:'900',color:colors.text},sub:{color:colors.holz,fontWeight:'800',fontSize:12,marginTop:5},desc:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:8},status:{paddingHorizontal:8,paddingVertical:5,borderRadius:radius.pill,alignSelf:'flex-start'},active:{backgroundColor:colors.successSoft},inactive:{backgroundColor:colors.surfaceAlt},statusText:{fontSize:9,fontWeight:'900'},imageHeader:{marginTop:28,marginBottom:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},imageTitle:{color:colors.text,fontSize:17,fontWeight:'900'},imageGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},imageWrap:{width:'47%'},image:{width:'100%',aspectRatio:1.35,borderRadius:radius.sm,backgroundColor:colors.surfaceAlt},deleteHint:{color:colors.muted,fontSize:9,textAlign:'center',marginTop:4}});
