import React, { useEffect, useState } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Button, Card, ErrorBanner, FormField, LoadingBlock, SectionHeader } from '../../components/ui';
import { useLanguage } from '../../context/LanguageContext';
import { supabase } from '../../lib/supabase';
import { colors, radius } from '../../theme';

type Settings = { id:number; hero_title:string; hero_title_de:string|null; hero_subtitle:string; hero_subtitle_de:string|null; hero_storage_path:string|null; address_line1:string|null; postal_code:string|null; city:string|null; country_code:string|null; seo_title_en:string|null; seo_title_de:string|null; seo_description_en:string|null; seo_description_de:string|null; updated_at:string };
export function HolzWebsiteView(){
  const {language}=useLanguage(); const de=language==='de'; const [s,setS]=useState<Settings|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  async function load(){const {data,error}=await supabase.from('frankiholz_site_settings').select('*').eq('id',1).single();if(error)setError(error.message);else setS(data as Settings);setLoading(false);}useEffect(()=>{load();},[]);
  async function save(){if(!s)return;setBusy(true);setError(null);const {id,updated_at,...payload}=s;const {error}=await supabase.from('frankiholz_site_settings').update(payload).eq('id',1);setBusy(false);if(error)setError(error.message);else await load();}
  async function hero(){if(!s)return;const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:'images',allowsEditing:true,quality:.85});if(r.canceled)return;setBusy(true);try{const a=r.assets[0];const body=await(await fetch(a.uri)).arrayBuffer();const ext=(a.mimeType?.split('/')[1]||'jpg').replace('jpeg','jpg');const path=`site/hero-${Date.now()}.${ext}`;const up=await supabase.storage.from('frankiholz-media').upload(path,body,{contentType:a.mimeType||'image/jpeg'});if(up.error)throw up.error;if(s.hero_storage_path)await supabase.storage.from('frankiholz-media').remove([s.hero_storage_path]);const {error}=await supabase.from('frankiholz_site_settings').update({hero_storage_path:path}).eq('id',1);if(error)throw error;setS({...s,hero_storage_path:path});}catch(e:any){setError(e.message??String(e));}finally{setBusy(false);}}
  if(loading)return <LoadingBlock/>; if(!s)return <ErrorBanner message={error??'Settings unavailable'}/>; const heroUrl=s.hero_storage_path?supabase.storage.from('frankiholz-media').getPublicUrl(s.hero_storage_path).data.publicUrl:null;
  return <><SectionHeader title={de?'Webseite & Unterkunft':'Website & property'} subtitle={de?'Hero-Inhalt, Adresse und SEO direkt aus der App ändern.':'Edit hero content, address and SEO directly from the app.'}/><ErrorBanner message={error}/>{heroUrl?<Image source={{uri:heroUrl}} style={styles.hero}/>:null}<Button variant="secondary" loading={busy} title={de?'Hero-Bild ändern':'Change hero image'} onPress={hero}/><View style={{height:14}}/>
    <Card><Text style={styles.group}>Deutsch</Text><FormField label="Hero Titel" value={s.hero_title_de??''} onChangeText={v=>setS({...s,hero_title_de:v})}/><FormField label="Hero Untertitel" value={s.hero_subtitle_de??''} onChangeText={v=>setS({...s,hero_subtitle_de:v})} multiline/><FormField label="SEO Titel" value={s.seo_title_de??''} onChangeText={v=>setS({...s,seo_title_de:v})}/><FormField label="SEO Beschreibung" value={s.seo_description_de??''} onChangeText={v=>setS({...s,seo_description_de:v})} multiline/></Card>
    <Card><Text style={styles.group}>English</Text><FormField label="Hero title" value={s.hero_title} onChangeText={v=>setS({...s,hero_title:v})}/><FormField label="Hero subtitle" value={s.hero_subtitle} onChangeText={v=>setS({...s,hero_subtitle:v})} multiline/><FormField label="SEO title" value={s.seo_title_en??''} onChangeText={v=>setS({...s,seo_title_en:v})}/><FormField label="SEO description" value={s.seo_description_en??''} onChangeText={v=>setS({...s,seo_description_en:v})} multiline/></Card>
    <Card><Text style={styles.group}>{de?'Adresse':'Address'}</Text><FormField label={de?'Straße / Adresse':'Street / address'} value={s.address_line1??''} onChangeText={v=>setS({...s,address_line1:v})}/><FormField label={de?'PLZ':'Postal code'} value={s.postal_code??''} onChangeText={v=>setS({...s,postal_code:v})}/><FormField label={de?'Stadt':'City'} value={s.city??''} onChangeText={v=>setS({...s,city:v})}/><FormField label={de?'Ländercode':'Country code'} value={s.country_code??''} onChangeText={v=>setS({...s,country_code:v.toUpperCase()})} autoCapitalize="characters"/></Card>
    <Button variant="holz" loading={busy} title={de?'Webseite speichern':'Save website'} onPress={save}/>
  </>;
}
const styles=StyleSheet.create({hero:{width:'100%',aspectRatio:1.8,borderRadius:radius.md,backgroundColor:colors.surfaceAlt,marginBottom:10},group:{color:colors.holz,fontWeight:'900',fontSize:16,marginBottom:14}});
